### PR TITLE
Add API support to Review

### PR DESCRIPTION
**Pull request by OulinG138**
Now API supports review use cases.

### CODE REVIEW

**Comment by HarryC493** [comment]
Nice extensions of the API! I will take some time to try these methods when implementing my review class. I also noticed some changes made to the Review classes in entities, and I believe these changes are necessary since Yelp API might not define restaurants the way we did in our software.

**Review by HarryC493 — CHANGES_REQUESTED** [review]
Please delete the user.csv and favourite.csv file and commit again to avoid future merge conflicts with our branches. Other than that, everything looks great.

**Comment by OulinG138** [comment]
> Please delete the user.csv and favourite.csv file and commit again to avoid future merge conflicts with our branches. Other than that, everything looks great.

Don't think it's possible to remove them since we require these two files for data writing purposes (Intellij prompts to refactor the filename when I try to delete them). But I'll keep in mind to tidy things up before each pull request.

**Comment by HarryC493** [comment]
> > Please delete the user.csv and favourite.csv file and commit again to avoid future merge conflicts with our branches. Other than that, everything looks great.
> 
> Don't think it's possible to remove them since we require these two files for data writing purposes (Intellij prompts to refactor the filename when I try to delete them). But I'll keep in mind to tidy things up before each pull request.

I've been deleting these csv files every time I make a pull request and had no trouble with it. These two files will be created whenever we run our program, so I don't think we need these files on Git pull requests for data writing purposes.

**Pull request merged**
