### PR TITLE
Resolve conflict

### PR DESCRIPTION
**Pull request by HarryC493**
Resolved merge conflict based on the discussion in the lab on Nov.13. The software is functioning from my end. Please close the pull request of API and search, and merge this branch to the main branch after code reviews.

### CODE REVIEW

**Comment by OulinG138** [comment]
Added ApiRestaurant class and its corresponding tests. Implemented necessary methods in FileUserDataAccessObject and made modifications to RestaurantFactory. Everything looks good！

**Review by OulinG138 — APPROVED** [review]
Added ApiRestaurant class and its corresponding tests. Implemented necessary methods in FileUserDataAccessObject and made modifications to RestaurantFactory. Everything looks good！

**Comment by HarryC493** [comment]
It turns out Git cannot merge csv files when there is a conflict. What I did was deleting the users.csv file from my end and commit again. Then the merge conflict on Github was resolved. Hope this helps.

**Comment by lisazhong13** [comment]
Thanks Harry for deleting the CSV file, it may be because CSV files have a special tabular structure that git knows nothing about. Everything runs well on my end when I pull from the main branch.

**Pull request merged**
