### PR TITLE
implemented the AddToFavouritesUseCase

### PR DESCRIPTION
**Pull request by choisar4**
Fully implemented the AddToFavourites Use Case. Have heavily modified RestaurantView class to accomodate for any bugs that I ran into. Program is running as expected. No conflicts with base branch.

### CODE REVIEW

**Review by HarryC493 — COMMENTED** [review]
Just a question out of curiosity, in the RestaurantView class, why is it necessary to execute the following code in the PropertyChange method?

info.removeAll();
info.revalidate();
info.repaint();

**Review by HarryC493 — APPROVED** [review]
I've pulled this branch to my local computer and run the program. Everything works as expected. I've also pulled the ViewFavouritesUseCase and run it, which also works well. Is it necessary to merge this branch before merging the ViewFavouritesUseCase branch? Or is it the case that I can merge the ViewFavouritesUseCase branch directly and close this pull request?

**Comment by choisar4** [comment]
The two branches are separate but they should both be merged into main to get full functionality.

**Comment by HarryC493** [comment]
> The ViewFavouritesUseCase is the only branch that needs to be merged. It has added functionality in addition to what was on this branch. Also, you're right it appears that the program runs smoothly with just "info.removeAll();". I think I must have added it while sandboxing for a way to update the Restaurant info. Feel free to remove if you'd like.

Got it. I will merge the ViewFavouriteUseCase pull request directly then.

**Pull request merged**
